---
- name: Enable selinux boolean haproxy_connect_any
  seboolean: 
    name: haproxy_connect_any 
    state: yes 
    persistent: yes

- name: Allow port 6443 for k3s apiserver
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled

- name: Install HAProxy on k3s load balancer
  yum:
    name: haproxy
  